package acpruntime

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// Permanent regressions from the independently reproduced fd3c935 review.
// Raw permission fixtures are intentionally not generated by the SDK DTOs.

const reviewPermissionParams = `{"sessionId":"s1","toolCall":{"toolCallId":"tc1","title":"Run command","kind":"execute","rawInput":{"command":"echo safe"}},"options":[{"optionId":"allow","name":"Allow","kind":"allow_once"},{"optionId":"deny","name":"Deny","kind":"reject_once"}]}`

func TestRegressionPermissionRequestStandardWire(t *testing.T) {
	var seen PermissionRequest
	peer := NewPeer(strings.NewReader(""), io.Discard, PeerOptions{})
	NewConnection(peer, Client{Authority: AuthorityHandlers{Permission: func(_ Context, req PermissionRequest) (PermissionDecision, error) {
		seen = req
		return PermissionDecision{Outcome: "selected", OptionID: "deny"}, nil
	}}})
	peer.handleRequest(context.Background(), rpcMessage{ID: json.RawMessage(`1`), Method: "session/request_permission", Params: json.RawMessage(reviewPermissionParams)})
	if seen.ToolCallID != "tc1" || seen.Title != "Run command" || seen.Kind != "execute" || len(seen.Options) != 2 || seen.Options[1].ID != "deny" {
		t.Fatalf("standard ACP permission fields lost: %+v", seen)
	}
}

func TestRegressionPermissionResponseStandardWire(t *testing.T) {
	var buf bytes.Buffer
	peer := NewPeer(strings.NewReader(""), &buf, PeerOptions{})
	NewConnection(peer, Client{})
	peer.handleRequest(context.Background(), rpcMessage{ID: json.RawMessage(`1`), Method: "session/request_permission", Params: json.RawMessage(reviewPermissionParams)})
	var msg struct {
		Result struct {
			Outcome json.RawMessage `json:"outcome"`
		} `json:"result"`
	}
	if err := json.Unmarshal(buf.Bytes(), &msg); err != nil {
		t.Fatal(err)
	}
	var outcome struct {
		Outcome  string `json:"outcome"`
		OptionID string `json:"optionId"`
	}
	if err := json.Unmarshal(msg.Result.Outcome, &outcome); err != nil {
		t.Fatalf("ACP requires nested outcome object; got wire %s; decode error: %v", buf.Bytes(), err)
	}
	if outcome.Outcome != "selected" || outcome.OptionID != "deny" {
		t.Fatalf("wrong fail-closed selection: %+v", outcome)
	}
}

func reviewPipeFactory(t *testing.T, register func(*Peer)) ConnectionFactory {
	t.Helper()
	return func(ctx context.Context, input ConnectionFactoryInput) (ConnectionHandle, error) {
		providerRead, hostWrite := io.Pipe()
		hostRead, providerWrite := io.Pipe()
		host := NewPeer(hostRead, hostWrite, PeerOptions{})
		provider := NewPeer(providerRead, providerWrite, PeerOptions{})
		provider.RegisterRequest("initialize", func(context.Context, json.RawMessage) (any, error) {
			return InitializeResponse{ProtocolVersion: 1, AgentCapabilities: AgentCapabilities{LoadSession: true, SessionCapabilities: SessionCapabilities{Resume: map[string]any{}, Close: map[string]any{}}}}, nil
		})
		provider.RegisterRequest("session/close", func(context.Context, json.RawMessage) (any, error) { return map[string]any{}, nil })
		register(provider)
		go host.Start(context.Background())
		go provider.Start(context.Background())
		var once sync.Once
		cleanup := func(context.Context) error {
			once.Do(func() {
				host.Close()
				provider.Close()
				hostRead.Close()
				hostWrite.Close()
				providerRead.Close()
				providerWrite.Close()
			})
			return nil
		}
		t.Cleanup(func() { cleanup(context.Background()) })
		return ConnectionHandle{Connection: NewConnection(host, input.Client), Dispose: cleanup}, nil
	}
}

func TestRegressionLoadResumePreserveRequestedSessionID(t *testing.T) {
	for _, method := range []string{"load", "resume"} {
		t.Run(method, func(t *testing.T) {
			factory := reviewPipeFactory(t, func(peer *Peer) {
				peer.RegisterRequest("session/"+method, func(context.Context, json.RawMessage) (any, error) { return map[string]any{}, nil })
			})
			r := NewRuntime(factory, RuntimeOptions{})
			ctx, cancel := context.WithTimeout(context.Background(), time.Second)
			defer cancel()
			start := StartSessionOptions{Agent: Agent{Type: "review", Command: "unused"}, CWD: t.TempDir()}
			var s *Session
			var err error
			if method == "load" {
				s, err = r.LoadSession(ctx, LoadSessionOptions{StartSessionOptions: start, SessionID: "existing-123"})
			} else {
				s, err = r.ResumeSession(ctx, ResumeSessionOptions{StartSessionOptions: start, SessionID: "existing-123"})
			}
			if err != nil {
				t.Fatal(err)
			}
			if got := s.Snapshot().Session.ID; got != "existing-123" {
				t.Fatalf("standard ACP %s response omits sessionId: got %q, want existing-123", method, got)
			}
		})
	}
}

func TestRegressionConcurrentUpdateAndFinishDoesNotPanic(t *testing.T) {
	for i := 0; i < 20000; i++ {
		d := newTestDriverWithActiveTurn(t, 64)
		a := d.currentTurn
		done := make(chan any, 1)
		go func() {
			defer func() { done <- recover() }()
			for j := 0; j < 100; j++ {
				d.handleSessionUpdate(SessionNotification{SessionID: "session-1", Update: SessionUpdate{SessionUpdate: "agent_message_chunk", Text: "x"}})
			}
		}()
		runtime.Gosched()
		d.finishTurn(a, TurnCompletion{}, context.Canceled)
		if p := <-done; p != nil {
			t.Fatalf("iteration %d: concurrent update/finish panicked: %v", i, p)
		}
	}
}

type reviewBlockingWriter struct {
	entered chan struct{}
	release chan struct{}
	once    sync.Once
}

func (w *reviewBlockingWriter) Write(p []byte) (int, error) {
	w.once.Do(func() { close(w.entered) })
	<-w.release
	return len(p), nil
}

func TestRegressionRPCCallDeadlineInterruptsBlockedWrite(t *testing.T) {
	w := &reviewBlockingWriter{entered: make(chan struct{}), release: make(chan struct{})}
	p := NewPeer(strings.NewReader(""), w, PeerOptions{})
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	done := make(chan error, 1)
	go func() { done <- p.Call(ctx, "session/prompt", map[string]any{}, nil) }()
	<-w.entered
	select {
	case <-done:
		close(w.release)
	case <-time.After(150 * time.Millisecond):
		close(w.release)
		<-done
		t.Fatal("Call remained inside writer.Write long after context deadline; cancellation cannot reach select")
	}
}

type reviewCountDriver struct {
	testSessionDriver
	closes atomic.Int32
}

func (d *reviewCountDriver) Close(context.Context) error { d.closes.Add(1); return nil }

func TestRegressionRuntimeClosesAllSameIDConnections(t *testing.T) {
	r := NewRuntime(nil, RuntimeOptions{})
	first, second := &reviewCountDriver{}, &reviewCountDriver{}
	a := r.register(first)
	r.register(second) // Loading the same durable session opens another connection.
	a.Close(context.Background())
	r.Close(context.Background())
	if second.closes.Load() != 1 {
		t.Fatalf("second connection with same sessionId was dropped from registry, close count=%d", second.closes.Load())
	}
}

func TestRegressionMetadataSnapshotIsImmutable(t *testing.T) {
	d := &acpSessionDriver{metadata: RuntimeSessionMetadata{AgentConfigOptions: []RuntimeAgentConfigOption{{ID: "model", Value: "original"}}}}
	m := d.Metadata()
	m.AgentConfigOptions[0].Value = "caller mutation"
	if got := d.Metadata().AgentConfigOptions[0].Value; got != "original" {
		t.Fatalf("snapshot mutation changed driver's internal metadata: %v", got)
	}
}

func TestRegressionTimedOutTurnDoesNotContaminateNextTurn(t *testing.T) {
	var prompts atomic.Int32
	firstStarted := make(chan struct{})
	releaseFirst := make(chan struct{})
	var release sync.Once
	defer release.Do(func() { close(releaseFirst) })
	factory := reviewPipeFactory(t, func(p *Peer) {
		p.RegisterRequest("session/new", func(context.Context, json.RawMessage) (any, error) { return NewSessionResponse{SessionID: "s1"}, nil })
		p.RegisterRequest("session/prompt", func(_ context.Context, raw json.RawMessage) (any, error) {
			if prompts.Add(1) == 1 {
				close(firstStarted)
				<-releaseFirst
			}
			_ = p.Notify(context.Background(), "session/update", SessionNotification{SessionID: "s1", Update: SessionUpdate{SessionUpdate: "agent_message_chunk", Text: "OLD"}})
			return PromptResponse{StopReason: "end_turn"}, nil
		})
	})
	r := NewRuntime(factory, RuntimeOptions{})
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	s, err := r.StartSession(ctx, StartSessionOptions{Agent: Agent{Type: "review", Command: "unused"}, CWD: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	firstCtx, firstCancel := context.WithCancel(ctx)
	first := s.StartTurn(firstCtx, RuntimePrompt{Text: "first"})
	<-firstStarted
	firstCancel()
	if result := <-first.Completion; result.Err == nil {
		t.Fatal("cancelled caller received success")
	}
	second := s.StartTurn(ctx, RuntimePrompt{Text: "second"})
	result := <-second.Completion
	if result.Err == nil {
		t.Fatalf("unconfirmed old turn reused transport: %+v", result.Completion)
	}
	release.Do(func() { close(releaseFirst) })
	if prompts.Load() != 1 {
		t.Fatalf("new prompt sent before old stop confirmation: %d", prompts.Load())
	}
}
