#!/usr/bin/env python3
"""Independent Draft 2020-12 stable schema gate; no production Go DTO imports.
Requires jsonschema==4.26.0. Positive wire JSON is authored from pinned official
schema definitions, never generated by the Go implementation under test.
"""
import hashlib
import json
import pathlib
from jsonschema import Draft202012Validator
ROOT = pathlib.Path(__file__).resolve().parent
lock = json.loads((ROOT / "schema-lock.json").read_text())
for release in lock["releases"]:
    path = ROOT / release["path"]
    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    assert actual == release["sha256"], (path, actual)
schema = json.loads((ROOT / "schema-v1.23.0/schema.json").read_text())
fixtures = {
    "permission-request": "RequestPermissionRequest",
    "permission-selected": "RequestPermissionResponse",
    "permission-rejected": "RequestPermissionResponse",
    "permission-cancelled": "RequestPermissionResponse",
    "usage-update": "SessionNotification",
    "boolean-option": "SessionConfigOption",
    "boolean-set": "SetSessionConfigOptionRequest",
    "elicitation-form": "CreateElicitationRequest",
    "elicitation-url": "CreateElicitationRequest",
    "elicitation-accept": "CreateElicitationResponse",
    "elicitation-complete": "CompleteElicitationNotification",
    "terminal-auth": "AuthMethod",
    "capabilities": "ClientCapabilities",
}
def validator(definition):
    return Draft202012Validator({"$ref": "#/$defs/" + definition, "$defs": schema["$defs"]})
for name, definition in fixtures.items():
    validator(definition).validate(json.loads((ROOT / "wire" / (name + ".json")).read_text()))
negatives = [
    ("RequestPermissionRequest", {"sessionId": "s", "toolCallId": "t", "options": []}),
    ("RequestPermissionRequest", {"sessionId": "s", "toolCall": {"toolCallId": "t"}, "options": [{"id": "a", "name": "Allow", "kind": "allow_once"}]}),
    ("RequestPermissionResponse", {"outcome": "selected", "optionId": "a"}),
    ("RequestPermissionResponse", {"outcome": {"outcome": "allow"}}),
    ("RequestPermissionResponse", {"outcome": {"outcome": "selected"}}),
    ("SessionConfigOption", {"type": "boolean", "id": "x", "name": "X", "currentValue": "false"}),
    ("SessionConfigOption", {"type": "boolean", "id": "x", "name": "X"}),
    ("SetSessionConfigOptionRequest", {"sessionId": "s", "configId": "x", "value": False}),
    ("SetSessionConfigOptionRequest", {"sessionId": "s", "configId": "x", "type": "boolean", "value": None}),
    ("UsageUpdate", {"usage": {"inputTokens": 1}}),
    ("ClientCapabilities", {"elicitation": {"form": True}}),
]
for definition, value in negatives:
    assert not validator(definition).is_valid(value), (definition, value)
print(f"Stable schema: {len(fixtures)} positive fixtures and {len(negatives)} negative contracts passed")
