"""Validate native fixtures with JSON Schema generated by the fixed stable CLI."""
import hashlib,json,pathlib
import jsonschema
root=pathlib.Path(__file__).parent/'codex-0.153.4'
manifest=json.loads((root/'manifest.json').read_text())
for name,sha in manifest['files_sha256'].items():
 assert hashlib.sha256((root/name).read_bytes()).hexdigest()==sha,name
fixtures=json.loads((root/'fixtures.json').read_text())
for fixture in fixtures:
 schema=json.loads((root/fixture['schema']).read_text())
 jsonschema.Draft7Validator(schema).validate(fixture['value'])
# Negative fixtures must fail independently of runtime custom decoders.
for schema_name,value in [('TurnInterruptParams.json',{'threadId':'thread'}),('TurnCompletedNotification.json',{'threadId':'thread','turn':{'id':'turn','items':[],'status':'unknown'}}),('CommandExecutionRequestApprovalResponse.json',{'decision':'approved'})]:
 schema=json.loads((root/schema_name).read_text())
 assert list(jsonschema.Draft7Validator(schema).iter_errors(value)),schema_name
print(f"PASS stable Codex {manifest['version']}: {len(fixtures)} positive, 3 negative fixtures; {len(manifest['files_sha256'])} schema digests verified")
